language: python
python:
- '3.6'
- 3.7-dev
install:
- pip install -r requirements.txt
- pip install -U setuptools
- python setup.py install
script:
- pytest
- compare-mt example/ted.ref.eng example/ted.sys1.eng example/ted.sys2.eng --decimals 2 --output_directory output
- compare-mt example/ted.ref.eng example/ted.sys1.eng example/ted.sys2.eng --compare_scores score_type=bleu,bootstrap=10 --output_directory output
- compare-mt example/ted.ref.eng example/ted.sys1.eng example/ted.sys2.eng --compare_word_accuracies bucket_type=freq,freq_corpus_file=example/ted.train.eng,bucket_cutoffs=1:2:3:5:10 --output_directory output
- compare-mt example/ted.ref.eng example/ted.sys1.eng example/ted.sys2.eng --compare_word_accuracies bucket_type=label,ref_labels=example/ted.ref.eng.tag,out_labels="example/ted.sys1.eng.tag;example/ted.sys2.eng.tag",label_set=CC+DT+IN+JJ+NN+NNP+NNS+PRP+RB+TO+VB+VBP+VBZ bucket_type=numlabel,ref_labels=example/ted.ref.eng.rptag,out_labels="example/ted.sys1.eng.rptag;example/ted.sys2.eng.rptag" --compare_ngrams compare_type=match,ref_labels=example/ted.ref.eng.tag,out_labels="example/ted.sys1.eng.tag;example/ted.sys2.eng.tag" --output_directory output
- compare-mt example/ted.ref.eng example/ted.sys1.eng example/ted.sys2.eng --src_file example/ted.orig.slk --compare_src_word_accuracies ref_align_file=example/ted.ref.align,out_align_files="example/ted.sys1.align;example/ted.sys2.align" --output_directory output
- compare-ll --ref example/ll_test.txt --ll-files example/ll_test.sys1.likelihood example/ll_test.sys2.likelihood --compare-word-likelihoods bucket_type=freq,freq_corpus_file=example/ll_test.txt --decimals 2
- compare-ll --ref example/ll_test.txt --ll-files example/ll_test.sys1.likelihood example/ll_test.sys2.likelihood --compare-word-likelihoods bucket_type=label,label_corpus=example/ll_test.tag,label_set=CC+DT+IN+JJ+NN+NNP+NNS+PRP+RB+TO+VB+VBP+VBZ
- compare-mt example/sum.ref.eng example/sum.sys1.eng example/sum.sys2.eng --compare_scores 'score_type=rouge1' 'score_type=rouge2' 'score_type=rougeL' --output_directory output
- python compare_mt/compare_mt_main.py example/ted.ref.eng example/ted.sys1.eng example/ted.sys2.eng --output_directory output
deploy:
  provider: pypi
  user: pmichel31415
  skip_existing: true
  password:
    secure: fGKIZDGfu5L2WGiGlIidPI5uBi2P2TIytEIDerK8sJWKdIM6CSLnzVVXHst5VIujIhF2/TP7YMniLvMEflW5HY7Bu5fb2dBMQnyQJiE8SE9ih/Oq35W3fHJCEiAYnWo3CKLYlwUyJC9VZn8w0JrU2MBWfLCIli3Fuh9sbRyVNvjRq4kc2IGIjcxwQvM0Hml9G/89UwWYKUbxi53tFfUr5qu9WyuPdy/i2bcHaYMB6FgXbTn47MmOgVDvLjLjePpMsF+fNQDkkN035ngPRLDfHfBM74ag2ycVUhjT8nsMOfKGMpmbk/CeyKOYT9TW6Fp/MALQ5nJ9qF4q49mOpz7lh0JfogTCxweU76cpPsi9j99BvYULTYy1SnjOP9ZqglobosWq2fUtw8Pf6KE57Y0ultfh+CAgXWhX7rBFGj9PrYW6+P8Y2p5+MQuXRZp+6TOXgpELh0SiXUAFQA5B77Kw8+tPw5DJL1b5oGXBTp94sttHxNXeV9bm9AwKB18rUcKKA0AHFP5FgjvdtfZKnjydSg/hFn82UA/0g0ubcSuqdoSRgk49NT4RasODiqnfqXseJ/q1vWm5eiW60QzXuHZrK6EN8vzKxFH7DYjAZTOQsAdoCgAQvSXABOKum/Pm3HWU+BfD0xZH9cJEn9YvSKD5qMNikmMK1LR2cgRHmbhjUXQ=
  on:
    branch: master
